error TS6059: File '/var/lib/jenkins/workspace/web3fygo_master/tests/api.test.ts' is not under 'rootDir' '/var/lib/jenkins/workspace/web3fygo_master/src'. 'rootDir' is expected to contain all source files.   The file is in the program because:     Matched by include pattern 'tests/**/*' in '/var/lib/jenkins/workspace/web3fygo_master/tsconfig.json' fix